name: Liquibase Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  LIQUIBASE_URL: ${{ secrets.DB_URL }}
  LIQUIBASE_USERNAME: ${{ secrets.DB_USERNAME }}
  LIQUIBASE_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'liquibase'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download Liquibase
      run: |
        wget https://github.com/liquibase/liquibase/releases/download/v4.3.5/liquibase-4.3.5.tar.gz
        tar xzf liquibase-4.3.5.tar.gz
        sudo mv liquibase-4.3.5 /usr/local/liquibase

    - name: Run Liquibase Update
      run: |
        /usr/local/liquibase/liquibase --url="${LIQUIBASE_URL}" --username="${LIQUIBASE_USERNAME}" --password="${LIQUIBASE_PASSWORD}" --changeLogFile=./liquibase/changelog.yml update