name: Liquibase Update

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  execute-liquibase-update:
    runs-on: ubuntu-latest
    environment: 'liquibase'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download Liquibase
      run: sudo snap install liquibase

    - name: Run Liquibase Update
      run: |
        liquibase --url ${{ secrets.DB_URL }} --username ${{ secrets.DB_USERNAME }} --password ${{ secrets.DB_PASSWORD }} --changeLogFile=./liquibase/changelog.yml update